/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ap.oefening7;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author maxim
 */
public class NewJFrame extends javax.swing.JFrame {

    Garage garage;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        Auto auto = new Gezinswagen(edu.ap.oefening7.Type.BENZINE, Merk.BMW, "02820802824082", "1-ABC-123", 1200, 5, false, 6);
        Auto auto2 = new Sportwagen(edu.ap.oefening7.Type.DIESEL, Merk.MERCEDES, "8223808238230823", "1-XYZ-789", 10, 12, 500);
        garage = new Garage();
        garage.addAuto(auto2);
        garage.addAuto(auto);
        garage.sort();
        buttonGroupSoortWagen.add(jRadioButtonSportwagen);
        buttonGroupSoortWagen.add(jRadioButtonGezinswagen);
        jComboBoxType.setModel(new DefaultComboBoxModel(edu.ap.oefening7.Type.values()));
        jComboBoxMerk.setModel(new DefaultComboBoxModel(Merk.values()));
        jPanelSportwagen.setVisible(true);
        jPanelGezinswagen.setVisible(false);
        jRadioButtonSportwagen.setSelected(true);
        updateLijst();
        DefaultListModel defaultListModel = new DefaultListModel();
        defaultListModel.addElement(auto);
        defaultListModel.addElement(auto2);
        jList1.setModel(defaultListModel);
    }

    private void swapPanels(boolean sportwagen) {
        jPanelSportwagen.setVisible(sportwagen);
        jPanelGezinswagen.setVisible(!sportwagen);
    }

    private void updateLijst() {
        jTextAreaAutolijstSportwagens.setText(garage.autolijstSportwagenToString());
        jTextAreaAutolijstGezinswagens.setText(garage.autolijstGezinswagenToString());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSoortWagen = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonSportwagen = new javax.swing.JRadioButton();
        jRadioButtonGezinswagen = new javax.swing.JRadioButton();
        jComboBoxType = new javax.swing.JComboBox<>();
        jComboBoxMerk = new javax.swing.JComboBox<>();
        jLabelChassisnummer = new javax.swing.JLabel();
        jTextFieldChassisnummer = new javax.swing.JTextField();
        jLabelNummerplaat = new javax.swing.JLabel();
        jTextFieldNummerplaat = new javax.swing.JTextField();
        jLabelKMStand = new javax.swing.JLabel();
        jTextFieldKMStand = new javax.swing.JTextField();
        jPanelSportwagen = new javax.swing.JPanel();
        jTextFieldPK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelGezinswagen = new javax.swing.JPanel();
        jCheckBoxTrekhaak = new javax.swing.JCheckBox();
        jLabelZitplaatsen = new javax.swing.JLabel();
        jTextFieldZitplaatsen = new javax.swing.JTextField();
        jButtonToevoegen = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAutolijstSportwagens = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAutolijstGezinswagens = new javax.swing.JTextArea();
        jButtonSorteerOpPK = new javax.swing.JButton();
        jButtonSorteerOpZitplaatsen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonSportwagen.setText("Sportwagen");
        jRadioButtonSportwagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSportwagenActionPerformed(evt);
            }
        });

        jRadioButtonGezinswagen.setText("Gezinswagen");
        jRadioButtonGezinswagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGezinswagenActionPerformed(evt);
            }
        });

        jLabelChassisnummer.setText("Chassisnummer");

        jLabelNummerplaat.setText("Nummerplaat");

        jLabelKMStand.setText("KM Stand");

        jLabel1.setText("PK");

        javax.swing.GroupLayout jPanelSportwagenLayout = new javax.swing.GroupLayout(jPanelSportwagen);
        jPanelSportwagen.setLayout(jPanelSportwagenLayout);
        jPanelSportwagenLayout.setHorizontalGroup(
            jPanelSportwagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSportwagenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSportwagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPK, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelSportwagenLayout.setVerticalGroup(
            jPanelSportwagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSportwagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jCheckBoxTrekhaak.setText("Trekhaak");

        jLabelZitplaatsen.setText("Zitplaatsen");

        javax.swing.GroupLayout jPanelGezinswagenLayout = new javax.swing.GroupLayout(jPanelGezinswagen);
        jPanelGezinswagen.setLayout(jPanelGezinswagenLayout);
        jPanelGezinswagenLayout.setHorizontalGroup(
            jPanelGezinswagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGezinswagenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelGezinswagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZitplaatsen)
                    .addComponent(jCheckBoxTrekhaak)
                    .addComponent(jTextFieldZitplaatsen, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanelGezinswagenLayout.setVerticalGroup(
            jPanelGezinswagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGezinswagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTrekhaak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelZitplaatsen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldZitplaatsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButtonToevoegen.setText("Toevoegen");
        jButtonToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToevoegenActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("yyyy-MM-dd")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonSportwagen)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonGezinswagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelSportwagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelGezinswagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonToevoegen)
                    .addComponent(jLabelKMStand)
                    .addComponent(jLabelNummerplaat)
                    .addComponent(jLabelChassisnummer)
                    .addComponent(jTextFieldChassisnummer)
                    .addComponent(jTextFieldNummerplaat)
                    .addComponent(jTextFieldKMStand, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSportwagen)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGezinswagen)
                    .addComponent(jComboBoxMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(jPanelSportwagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGezinswagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelChassisnummer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldChassisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNummerplaat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNummerplaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKMStand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldKMStand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonToevoegen))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Auto toevoegen", jPanel1);

        jTextAreaAutolijstSportwagens.setColumns(20);
        jTextAreaAutolijstSportwagens.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAutolijstSportwagens);

        jTextAreaAutolijstGezinswagens.setColumns(20);
        jTextAreaAutolijstGezinswagens.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAutolijstGezinswagens);

        jButtonSorteerOpPK.setText("Sorteer op pk");
        jButtonSorteerOpPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSorteerOpPKActionPerformed(evt);
            }
        });

        jButtonSorteerOpZitplaatsen.setText("Sorteer op zitplaatsen");
        jButtonSorteerOpZitplaatsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSorteerOpZitplaatsenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonSorteerOpPK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSorteerOpZitplaatsen)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSorteerOpPK)
                    .addComponent(jButtonSorteerOpZitplaatsen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Autolijst", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonSportwagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSportwagenActionPerformed
        if (jRadioButtonSportwagen.isSelected()) {
            swapPanels(true);
        }
    }//GEN-LAST:event_jRadioButtonSportwagenActionPerformed

    private void jRadioButtonGezinswagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGezinswagenActionPerformed
        if (jRadioButtonGezinswagen.isSelected()) {
            swapPanels(false);
        }
    }//GEN-LAST:event_jRadioButtonGezinswagenActionPerformed

    private void jButtonToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToevoegenActionPerformed
        if (jRadioButtonSportwagen.isSelected()) {
            //Type type, Merk merk, String chassisnummer, String nummerplaat, double kilometerstand, double kilometerFactor, double pk
            Auto auto = new Sportwagen(edu.ap.oefening7.Type.valueOf(jComboBoxType.getSelectedItem().toString()), Merk.valueOf(jComboBoxMerk.getSelectedItem().toString()), jTextFieldChassisnummer.getText(), jTextFieldNummerplaat.getText(), Double.parseDouble(jTextFieldKMStand.getText()), 5, Double.parseDouble(jTextFieldPK.getText()));
            garage.addAuto(auto);
        } else {
            Auto auto = new Gezinswagen(edu.ap.oefening7.Type.valueOf(jComboBoxType.getSelectedItem().toString()), Merk.valueOf(jComboBoxMerk.getSelectedItem().toString()), jTextFieldChassisnummer.getText(), jTextFieldNummerplaat.getText(), Double.parseDouble(jTextFieldKMStand.getText()), Integer.parseInt(jTextFieldZitplaatsen.getText()), jCheckBoxTrekhaak.isSelected(), 5);
            garage.addAuto(auto);
        }
        updateLijst();
    }//GEN-LAST:event_jButtonToevoegenActionPerformed

    private void jButtonSorteerOpPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSorteerOpPKActionPerformed
        garage.sort(new SortByPK());
        updateLijst();
    }//GEN-LAST:event_jButtonSorteerOpPKActionPerformed

    private void jButtonSorteerOpZitplaatsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSorteerOpZitplaatsenActionPerformed
        garage.sort(new SorteerByZitplaatsen());
        updateLijst();
    }//GEN-LAST:event_jButtonSorteerOpZitplaatsenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSoortWagen;
    private javax.swing.JButton jButtonSorteerOpPK;
    private javax.swing.JButton jButtonSorteerOpZitplaatsen;
    private javax.swing.JButton jButtonToevoegen;
    private javax.swing.JCheckBox jCheckBoxTrekhaak;
    private javax.swing.JComboBox<String> jComboBoxMerk;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChassisnummer;
    private javax.swing.JLabel jLabelKMStand;
    private javax.swing.JLabel jLabelNummerplaat;
    private javax.swing.JLabel jLabelZitplaatsen;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelGezinswagen;
    private javax.swing.JPanel jPanelSportwagen;
    private javax.swing.JRadioButton jRadioButtonGezinswagen;
    private javax.swing.JRadioButton jRadioButtonSportwagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaAutolijstGezinswagens;
    private javax.swing.JTextArea jTextAreaAutolijstSportwagens;
    private javax.swing.JTextField jTextFieldChassisnummer;
    private javax.swing.JTextField jTextFieldKMStand;
    private javax.swing.JTextField jTextFieldNummerplaat;
    private javax.swing.JTextField jTextFieldPK;
    private javax.swing.JTextField jTextFieldZitplaatsen;
    // End of variables declaration//GEN-END:variables
}
